[package]
name = "lucrecia"
version = "0.1.0"
authors = ["Mukund Lakshman <yaymukund@gmail.com>"]
edition = "2018"

[dependencies]
cursive = "0.10"
crossbeam-utils = "0.6"
env_logger = "0.6.0"
log = "0.4"
mpv = { git = "https://github.com/ParadoxSpiral/mpv-rs" }
