[package]
name = "lucrecia"
version = "0.1.0"
authors = ["Mukund Lakshman <yaymukund@gmail.com>"]
edition = "2018"

[dependencies]
# mpv = { git = "https://github.com/ParadoxSpiral/mpv-rs" }
cursive = "0.10"
mpv = { path = "../mpv-rs" }
crossbeam-utils = "0.6"
