version: 2.1
jobs:
  build:
    docker:
      - image: yaymukund/cci-rust-roja:0.0.3
    steps:
      - checkout
      - run: cargo --version
      - run: cargo build --release --all-targets

      - store_artifacts:
          path: target/release/roja

      - store_artifacts:
          path: target/release/roja-build-database
